{
 "title": "Energieverbruik",
 "description": "Overzicht van elektriciteits- en gasverbruik in huis",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Elektriciteit actueel",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Gas actueel",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "m3/h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hourly_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Afgelopen uur",
   "type": "graph",
   "description": "Elektriciteitsgebruik in het afgelopen uur",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "watt", "label": "Power" }
   ],
   "targets": [
    {
     "alias": "Elektriciteit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " * 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    },
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "m3/h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hourly_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Afgelopen 24 uur",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "kwatt", "label": "Elektriciteit" }
   ],
   "targets": [
    {
     "alias": "Elektriciteit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kW",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption" }
     ]
    },
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "m3/h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "hourly_gas_consumption" }
     ]
    }
   ]
  },
  {
   "title": "Elektriciteit afgelopen 7 dagen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "Laag tarief",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'power_consumption_low') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption_low" }
     ]
    },
    {
     "alias": "Normaal tarief",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "kWh",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"kWh\" WHERE (\"entity_id\" = 'power_consumption_normal') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "power_consumption_normal" }
     ]
    }
   ]
  },
  {
   "title": "Gas afgelopen 7 dagen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "alias": "Gas",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "m3",
     "query": "SELECT last(\"value\") - first(\"value\") FROM \"m3\" WHERE (\"entity_id\" = 'gas_consumption') AND $timeFilter GROUP BY time(1d)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "entity_id", "operator": "=", "value": "gas_consumption" }
     ]
    }
   ]
  }
 ]
}